project:
  name: smart-network-optimization
  seed: 42

data:
  dir: data
  logs_file: router_logs_15_days.csv
  topology_file: network_topology.csv
  config_changes_file: configuration_history.csv
  app_usage_file: application_usage.csv
  user_activity_file: user_activity.csv
  external_events_file: external_factors.csv

features:
  window: 6          # number of past intervals to aggregate (e.g., hours)
  lags: [1, 2, 3]    # simple lag features
  rolling_windows: [3, 6]
  target_horizon: 1  # predict 1 step ahead
  threshold: 0.5     # classification probability threshold

model:
  type: "logreg"     # [logreg, random_forest]
  logreg:
    C: 1.0
    max_iter: 200
  random_forest:
    n_estimators: 200
    max_depth: 8

paths:
  models_dir: models
  outputs_dir: outputs
